# Generated by Django 5.2.5 on 2025-08-19 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coins',
            name='apiurl',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='coins',
            name='logourl',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='coins',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
