# Generated by Django 5.2.5 on 2025-08-19 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_coins_apiurl_alter_coins_logourl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coins',
            name='symbol',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
